// Builds the chat panel script from src/chat/ui/panel/main.ts (real ES modules) into ONE browser
// IIFE and writes it into src/chat/ui/panel.generated.ts as a string constant. WHY a committed
// generated file, like mdLibs.generated.ts: core is consumed as raw .ts by every surface's bundler
// and typechecker, so chatHtml() must inline the panel with zero runtime file access, and an
// ignored artifact would add a mandatory pre-step to every tsc/tsup/vsce invocation.
// panel.generated.spec.ts rebuilds the bundle in-process and fails when the committed file is stale.
//
//   pnpm build:panel            rebuild once
//   pnpm build:panel --watch    rebuild on every change under panel/
import { build, type Options } from "tsup";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const CORE_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = join(CORE_ROOT, "src", "chat", "ui", "panel", "main.ts");
const DEST = join(CORE_ROOT, "src", "chat", "ui", "panel.generated.ts");
const OUT_NAME = "panel.global.js"; // tsup's file name for an iife entry called "panel"

function buildOptions(outDir: string): Options {
  return {
    entry: { panel: ENTRY },
    format: ["iife"],
    platform: "browser",
    target: "es2022",
    // tsup resolves a tsconfig from process.cwd() unless told otherwise, so without this the
    // output depended on the invoking directory: the panel's own config is the one that
    // describes these modules, and the strict directive is emitted deliberately below
    // instead of being inherited from whichever tsconfig happened to be found.
    tsconfig: join(CORE_ROOT, "src", "chat", "ui", "panel", "tsconfig.json"),
    banner: { js: '"use strict";' },
    // tsup's rollup treeshake pass rewrote data (it dropped CHAT_MODEL_OPTIONS properties and an
    // unused `let` write when this migration was tried); esbuild alone keeps the code verbatim.
    treeshake: false,
    minify: false,
    sourcemap: false,
    dts: false,
    splitting: false,
    clean: false,
    silent: true,
    config: false,
    outDir,
    esbuildOptions(o) {
      o.charset = "utf8"; // keep the Korean UI strings literal instead of \u escapes
      o.legalComments = "none";
      o.absWorkingDir = CORE_ROOT; // path comments must not depend on the invoking cwd (determinism)
    },
  };
}

// The un-escape sentinels: the legacy script was a template literal whose backslashes were
// doubled, so a surviving `\\n` or a `</script` would mean the cut regressed to escaped text.
function assertBundle(js: string): void {
  const fail = (why: string) => { throw new Error("panel bundle: " + why); };
  if (!js.startsWith('"use strict";')) fail("does not start with \"use strict\"");
  if (js.includes("</script")) fail("contains </script (would end the inline <script> tag)");
  if (js.includes("process.")) fail("contains process. (node-only code reached the browser bundle)");
  if (js.includes("require(")) fail("contains require( (a CommonJS dependency reached the bundle)");
  const escaped = js.split("\n").filter((l) => l.includes("\\\\n") && !l.trim().startsWith("//"));
  if (escaped.length) fail("double-escaped newline outside a comment: " + escaped[0].trim().slice(0, 80));
}

export async function bundlePanel(): Promise<string> {
  const outDir = mkdtempSync(join(tmpdir(), "agentnet-panel-"));
  try {
    await build(buildOptions(outDir));
    const js = readFileSync(join(outDir, OUT_NAME), "utf8");
    assertBundle(js);
    return js;
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
}

// A JSON string literal is a valid JS string literal: no decoder is needed and the text stays
// grep-able; non-ASCII stays literal (the file is UTF-8 like webview.ts).
export function renderPanelModule(js: string): string {
  return (
    "// AUTO-GENERATED by scripts/buildPanel.ts from src/chat/ui/panel/ -- DO NOT EDIT; re-run pnpm build:panel\n" +
    `export const PANEL_SCRIPT = ${JSON.stringify(js)};\n`
  );
}

function writeGenerated(js: string): void {
  writeFileSync(DEST, renderPanelModule(js), "utf8");
  console.log(`wrote ${DEST} (${(js.length / 1024).toFixed(0)} KB)`);
}

async function main(): Promise<void> {
  if (!process.argv.includes("--watch")) {
    writeGenerated(await bundlePanel());
    return;
  }
  // watch mode keeps its temp dir for the process lifetime; each successful rebuild rewrites DEST
  const outDir = mkdtempSync(join(tmpdir(), "agentnet-panel-watch-"));
  await build({
    ...buildOptions(outDir),
    watch: true,
    onSuccess: async () => {
      const js = readFileSync(join(outDir, OUT_NAME), "utf8");
      assertBundle(js);
      writeGenerated(js);
    },
  });
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((e) => { console.error(e); process.exit(1); });
}
