// Generates src/chat/ui/mdLibs.generated.ts — the marked + dompurify browser builds
// inlined as a string constant. The chat webview ships this into a <script> tag.
//
// WHY a checked-in generated file (not a runtime readFileSync): core is consumed as
// raw .ts (its package `exports` point at ./src/*.ts), so each surface's bundler
// inlines core's source directly. A runtime readFileSync(createRequire(...)) breaks
// once bundled — import.meta.url shifts to the host's dist/, whose node_modules has
// no marked/dompurify (they're core's deps, not the host's). Baking the libs into a
// source constant means the bundler embeds them as text — zero runtime file lookup.
//
// Re-run after bumping marked/dompurify:  node scripts/genMdLibs.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);

// Strict `exports` maps block ./lib/* subpaths, so resolve each package's MAIN entry
// (always allowed), walk up to the package root, then read the browser build.
function pkgRoot(name) {
  const main = require.resolve(name);
  const marker = `${name}/`;
  const i = main.lastIndexOf(marker);
  return i >= 0 ? main.slice(0, i + marker.length) : dirname(main);
}

const marked = readFileSync(join(pkgRoot("marked"), "lib", "marked.umd.js"), "utf8");
const purify = readFileSync(join(pkgRoot("dompurify"), "dist", "purify.min.js"), "utf8");

// Embed via a base64 literal + decode at module load: keeps the (large, regex-heavy)
// library text out of the TS source byte-for-byte, so no escaping/template pitfalls.
const b64 = Buffer.from(marked + "\n" + purify, "utf8").toString("base64");

const out = `// AUTO-GENERATED by scripts/genMdLibs.mjs — DO NOT EDIT.
// marked (md → html) + dompurify (XSS sanitize), browser builds, inlined for the
// chat webview's <script>. Re-generate after bumping either dep.
//
// Stored as base64 (the library text is regex-heavy — base64 sidesteps every string
// escaping pitfall in this source file). Evaluated on the node host (vscode/localhost,
// where chatHtml() inlines the decoded text into a <script>) AND in the browser (the
// React webview surface imports MD_LIBS directly). atob + TextDecoder exist in both;
// Buffer does NOT exist in the browser, so we don't use it.
const MD_LIBS_B64 =
  "${b64}";

function __decodeMdLibs(b64: string): string {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder("utf-8").decode(bytes);
}

export const MD_LIBS: string = __decodeMdLibs(MD_LIBS_B64);
`;

const dest = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "chat", "ui", "mdLibs.generated.ts");
writeFileSync(dest, out, "utf8");
console.log(`wrote ${dest} (${(b64.length / 1024).toFixed(0)} KB base64)`);
